Unbundle SYMPHONY sources.
git-svn-id: svn://svn.r-forge.r-project.org/svnroot/rsymphony@58 edb9625f-4e0d-4859-8d74-9fd3b1da38cb

diff --git a/pkg/configure b/pkg/configure
--- a/pkg/configure
+++ b/pkg/configure
@@ -43,33 +43,14 @@ status=${?}
 
 rm -f conftest.*
 
-if test ${status} -eq 0; then
-    SYMPHONY_INCLUDE_PATH=
-    SYMPHONY_LIB_PATH=
-    SYMPHONY_TS=
-else    
-    (cd src/SYMPHONY && \
-	./configure \
-	--enable-static --disable-shared --with-pic \
-        --with-application=no --disable-dependency-tracking \
-	--disable-zlib --disable-bzlib\
-        --disable-cplex-libcheck --disable-glpk-libcheck \
-        --disable-osl-libcheck --disable-soplex-libcheck \
-        --disable-xpress-libcheck \
-	CC="`${R} CMD config CC`" \
-	CPP="`${R} CMD config CPP`" \
-	CXX="`${R} CMD config CXX`" \
-	CXXCPP="`${R} CMD config CXXCPP`" \
-	F77="`${R} CMD config F77`" \
-	FLIBS="`${R} CMD config FLIBS`")
-    SYMPHONY_LIBS="-lSym -lCgl -lOsiClp -lClp -lOsi -lCoinUtils"
-    SYMPHONY_INCLUDE_PATH="-ISYMPHONY/include"
-    SYMPHONY_LIB_PATH="-LSYMPHONY/lib"
-    SYMPHONY_TS="SYMPHONY.ts"
+if test ${status} -ne 0; then
+  echo "Cannot find SYMPHONY libraries and headers."
+  echo "See <https://projects.coin-or.org/SYMPHONY>."
+  exit 1
 fi
 
-sed -e "s|@SYMPHONY_LIBS@|${SYMPHONY_LIBS}|" \
-    -e "s|@SYMPHONY_INCLUDE_PATH@|${SYMPHONY_INCLUDE_PATH}|" \
-    -e "s|@SYMPHONY_LIB_PATH@|${SYMPHONY_LIB_PATH}|" \
-    -e "s|@SYMPHONY_TS@|${SYMPHONY_TS}|" \
+sed -e "s|@SYMPHONY_CPPFLAGS@|${SYMPHONY_CPPFLAGS}|" \
+    -e "s|@SYMPHONY_LIBS@|${SYMPHONY_LIBS}|" \
     src/Makevars.in > src/Makevars
+
+exit 0
