Use a system-wide SYMPHONY installation if available.
git-svn-id: svn://svn.r-forge.r-project.org/svnroot/rsymphony@13 edb9625f-4e0d-4859-8d74-9fd3b1da38cb

diff --git a/pkg/configure b/pkg/configure
--- a/pkg/configure
+++ b/pkg/configure
@@ -1,10 +1,57 @@
 #! /bin/sh
 ## For the time being, this is a simple shell script ...
 
-cd src/SYMPHONY && \
-  ./configure --enable-static --disable-shared --with-pic \
-              --with-application=no --disable-dependency-tracking \
-	      --disable-cplex-libcheck --disable-glpk-libcheck \
-	      --disable-osl-libcheck --disable-soplex-libcheck \
-              --disable-xpress-libcheck
+## Test whether a complete SYMPHONY library environment is available,
+## e.g. https://projects.coin-or.org/CoinBinary.
 
+## Find the R home directory.
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+  echo "Could not determine R_HOME."
+  exit 1
+fi
+
+SYMPHONY_LIBS="-lSym -lCgl -lOsiClp -lClp -lOsi -lCoinUtils"
+
+## Test whether we can compile and link a minimal program.
+rm -f conftest.*
+
+cat > conftest.cc <<EOF
+#include <symphony.h>
+extern "C"
+int
+main ()
+{
+    sym_environment *env = sym_open_environment();
+    sym_close_environment(env);
+    return 0;
+}
+EOF
+
+"${R_HOME}/bin/R" CMD SHLIB conftest.cc ${SYMPHONY_LIBS} 2>&1 >/dev/null
+status=${?}
+
+rm -f conftest.*
+
+if test ${status} -eq 0; then
+    SYMPHONY_INCLUDE_PATH=
+    SYMPHONY_LIB_PATH=
+    SYMPHONY_TS=
+else    
+    (cd src/SYMPHONY && \
+	./configure \
+	--enable-static --disable-shared --with-pic \
+        --with-application=no --disable-dependency-tracking \
+        --disable-cplex-libcheck --disable-glpk-libcheck \
+        --disable-osl-libcheck --disable-soplex-libcheck \
+        --disable-xpress-libcheck)
+    SYMPHONY_INCLUDE_PATH="-ISYMPHONY/include"
+    SYMPHONY_LIB_PATH="-LSYMPHONY/lib"
+    SYMPHONY_TS="SYMPHONY.ts"
+fi
+
+sed -e "s|@SYMPHONY_INCLUDE_PATH@|${SYMPHONY_INCLUDE_PATH}|" \
+    -e "s|@SYMPHONY_LIB_PATH@|${SYMPHONY_LIB_PATH}|" \
+    -e "s|@SYMPHONY_TS@|${SYMPHONY_TS}|" \
+    src/Makevars.in > src/Makevars
+    
